create table users (
     id bigint generated by default as identity,
     name varchar(500),
     email varchar(200),
     userManagerId bigint,
     regDttm timestamp,
     PRIMARY KEY (id)
);

create table user_managers (
     id bigint generated by default as identity primary key,
     name varchar(500),
     regDttm timestamp
);